### ISSUE TITLE
Cypress TypeError

### ISSUE THREAD

**Issue by shaYaman** [atlanteh/israeli-id-validator#7]
Getting this error when using this:
`console.log(isIsraeliIdValid(123456782)) // true`
(0 , israeli_id_validator_1.default) is not a function

**Comment by atlanteh** [comment]
Can you please provide a simple minimal reproducible example that I can check? I've never used cypress before so if you provide a simple example I'll be able to take a look.

**Comment by shaYaman** [comment]
// console.log(isIsraeliIdValid(String(123456782))) // true
// let InitID = (Cypress._.random(0, 1e10))
// cy.log('This is the initial ID: '+InitID)
// let CurrentID = InitID
// for (let i = 0; i < 20; i++) {
// if (isIsraeliIdValid(String(CurrentID)) == true) {
// cy.log(String((CurrentID) + " is " +
((isIsraeliIdValid(String(CurrentID))) ? "a valid" : "an invalid") + "
Israeli ID"));

// //cy.get('div.form-group:nth-child(2) > div:nth-child(1) >
input:nth-child(2)').should('have.attr', 'type' ,'text').type(CurrentID)
// break
// } else {
// CurrentID = ++CurrentID
// cy.log(String((CurrentID) + " is " +
(isIsraeliIdValid(String(CurrentID)) ? "a valid" : "an invalid") + "
Israeli ID"));
// }
// }

תודה,
שי מנחם
054-5245225

**Comment by atlanteh** [comment]
I'm sorry, this doesn't help me understand the issue.
Can you provide a small repo with the cypress configuration set up and this example so I can easily just run `npm i` and reproduce this issue?
